import { Node } from 'estree';
import MagicString from 'magic-string';

// @ts-ignore
import { version } from '../../../package.json';

export default (parsed: Node, s: MagicString, file: string, runtime: string = 'reactive-assignments'): MagicString => {
	s.prepend(`import * as $$store from '${runtime}';\n\n`);

	if (file) s.prepend(`// ${file} generated by reactive-assignments v${version}\n`);

	return s;
};
