import { Node } from 'estree';
import MagicString from 'magic-string';

// @ts-ignore
import { version } from '../../../package.json';

export default (parsed: Node, s: MagicString, file: string, reactivejs: string = 'reactivejs'): MagicString => {
	s.prepend(`import * as $$store from '${reactivejs}';\n\n`);

	if (file) s.prepend(`// ${file} generated by ReactiveJS v${version}.`);

	return s;
};
